version: "3"
services:
  mysql:
    container_name: mysql
    build: ./docker/mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
#    networks:
#      extnetwork:
#        ipv4_address: 172.199.0.3
  app:
    container_name: app
    build: ./docker/java
    image: app
    ports:
      - "18080:18080"
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./exam1.log:/exam1.log
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
#      MYSQL_IP: 172.199.0.3
      MYSQL_IP: mysql
      MYSQL_PORT: 3306
#    networks:
#        extnetwork:
#          ipv4_address: 172.199.0.2
#networks:
#  extnetwork:
#    driver: bridge
#    ipam:
#      config:
#      - subnet: 172.199.0.0/16